[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && VITE_API_URL= npm run build && cd .. && rm -rf backend/public && cp -r frontend/dist backend/public && cd backend && npm install && npm run build"

[deploy]
startCommand = "cd backend && NODE_ENV=production npm run start:prod"
healthcheckPath = "/products"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
