services:
  - type: web
    name: edpulse-app
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && VITE_API_URL= npm run build && cd .. && rm -rf backend/public && cp -r frontend/dist backend/public && cd backend && npm install && npm run build
    startCommand: cd backend && NODE_ENV=production npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: ""
    healthCheckPath: /products
